rules:
  indentation:
    - 1
    - size: 'tab'
  property-sort-order:
    - 0
  hex-length:
    - 0
  leading-zero:
    - 0
  force-attribute-nesting:
   - 0
  no-qualifying-elements:
   - 0
  no-color-literals:
   - 0
  force-pseudo-nesting:
   - 0
  force-element-nesting:
   - 0
  no-important:
   - 0
  nesting-depth:
   - 4
